version: '3'
services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    ports:
      - 443:443
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/deletethis/certificate.crt:/etc/nginx/certificate.crt
      - ./requirements/nginx/deletethis/private.key:/etc/nginx/private.key
    depends_on:
      - wordpress
    networks:
      - internalNetwork
    # restart: unless-stopped

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    depends_on:
      - db
    networks:
      - internalNetwork
    # restart: unless-stopped

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    volumes:
      - ./mariadb/db-data:/var/lib/mysql
    networks:
      - internalNetwork
    # restart: unless-stopped

networks:
  internalNetwork:
