version: '3'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - default
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - default
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DATABASE=${DATABASE}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - default
    env_file:
      - .env
    environment:
      ROOT_PASSWORD: ${ROOT_PASSWORD}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      DATABASE: ${DATABASE}
    restart: unless-stopped

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/fkernbac/data/wordpress_data
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/fkernbac/data/mariadb_data
      o: bind

networks:
  default:
    external:
      name: externalNetwork
