version: '3'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CERT=${CERT}
      - KEY=${KEY}
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=${WP_PASSWORD}
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/fkernbac/data/wordpress_data
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/fkernbac/data/mariadb_data
      o: bind

networks:
  inception:
    driver: bridge
