version: '3'
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress
    networks:
      - internalNetwork
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./requirements/wordpress/wp-content:/var/www/html/wp-content
    depends_on:
      - mariadb
    networks:
      - internalNetwork
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - ./requirements/mariadb/db-data:/var/lib/mysql
    networks:
      - internalNetwork
    restart: unless-stopped

networks:
  internalNetwork:
    driver: bridge
