CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'fkernbac'@'%' IDENTIFIED BY 'anuba';
GRANT ALL PRIVILEGES ON wordpress.* TO 'fkernbac'@'%' IDENTIFIED BY 'anuba';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'anuba';
FLUSH PRIVILEGES;
SHOW DATABASES;
