CREATE DATABASE ${DB_NAME};
CREATE USER '${DB_USER}'@'%' IDENTIFIED by '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON "${DB_NAME}.*" TO "${DB_USER}"@'%';
ALTER USER 'root'@'localhost' IDENTIFIED by '${ADMIN_PASSWORD}';
FLUSH PRIVILEGES;
